services:
  mongodb:
    image: mongo:4
    networks:
      - superdesk
    expose:
      - '27017'

  redis:
    image: redis:3
    networks:
      - superdesk
    expose:
      - '6379'

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    networks:
      - superdesk
    expose:
      - '9200'

  superdesk-server:
    image: sourcefabricoss/superdesk-server:latest
    depends_on:
      - redis
      - mongodb
      - elastic
    environment:
      - SUPERDESK_URL=https://api-cms.cncnews.co/api
      - DEMO_DATA=1
      - WEB_CONCURRENCY=2
      - SUPERDESK_CLIENT_URL=https://cms.cncnews.co
      - CONTENTAPI_URL=https://api-cms.cncnews.co/capi
      - MONGO_URI=mongodb://mongodb/superdesk
      - CONTENTAPI_MONGO_URI=mongodb://mongodb/superdesk_capi
      - PUBLICAPI_MONGO_URI=mongodb://mongodb/superdesk_papi
      - LEGAL_ARCHIVE_URI=mongodb://mongodb/superdesk_legal
      - ARCHIVED_URI=mongodb://mongodb/superdesk_archive
      - ELASTICSEARCH_URL=http://elastic:9200
      - ELASTICSEARCH_INDEX=superdesk
      - CELERY_BROKER_URL=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/1
      - DEFAULT_TIMEZONE=America/Sao_Paulo
      - SECRET_KEY=*k^&9)byk=8en9n1sg7-xj4f8wr2mh^x#t%_2=1=z@69oxt50!
      - ENV=production
    networks:
      - superdesk
      - superdesk-newsroom
    expose:
      - '8080'

  superdesk-client:
    image: sourcefabricoss/superdesk-client:latest
    depends_on:
      - superdesk-server
    environment:
      - SUPERDESK_URL=https://api-cms.cncnews.co/api
      - SUPERDESK_WS_URL=wss://api-cms.cncnews.co/ws
      - IFRAMELY_KEY
      - ENV=production
    networks:
      - superdesk

networks:
  superdesk:
    driver: bridge
  superdesk-newsroom:
    name: superdesk-newsroom
